# Generated by Django 4.0.3 on 2022-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
