# Generated by Django 4.0.3 on 2022-03-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=70)),
                ('identification_number', models.CharField(max_length=20)),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.identificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('date_arrival', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaru_process.category')),
                ('state_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaru_process.stateproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaru_process.supplier')),
            ],
        ),
    ]
